/**
 * PackageJsonGenerator - Generates package.json files for different frameworks
 *
 * Supports:
 * - React (Create React App)
 * - Next.js
 * - Vue
 * - HTML (static)
 *
 * Validates: Build Mode Requirements - Project Initialization
 */

export interface PackageJsonConfig {
    projectName: string;
    framework: 'react' | 'nextjs' | 'vue' | 'flutter' | 'html';
    version?: string;
    description?: string;
}

export interface PackageJson {
    name: string;
    version: string;
    description?: string;
    private: boolean;
    scripts: Record<string, string>;
    dependencies: Record<string, string>;
    devDependencies?: Record<string, string>;
    [key: string]: any; // Allow additional properties like eslintConfig, browserslist
}

export class PackageJsonGenerator {
    /**
     * Generate a package.json object for the specified framework
     */
    generate(config: PackageJsonConfig): PackageJson {
        const { projectName, framework, version = '1.0.0', description } = config;

        // Sanitize project name for npm
        const npmName = this.sanitizeNpmName(projectName);

        const basePackage: PackageJson = {
            name: npmName,
            version,
            description: description || `${projectName} - Generated by Personaut`,
            private: true,
            scripts: {},
            dependencies: {},
        };

        switch (framework) {
            case 'react':
                return this.generateReactPackage(basePackage);
            case 'nextjs':
                return this.generateNextJsPackage(basePackage);
            case 'vue':
                return this.generateVuePackage(basePackage);
            case 'html':
                return this.generateHtmlPackage(basePackage);
            case 'flutter':
                // Flutter doesn't use package.json, return minimal config
                return this.generateFlutterPackage(basePackage);
            default:
                throw new Error(`Unsupported framework: ${framework}`);
        }
    }

    /**
     * Sanitize project name to be npm-compatible
     * - Lowercase
     * - Replace spaces and special chars with hyphens
     * - Remove leading/trailing hyphens
     */
    private sanitizeNpmName(name: string): string {
        return name
            .toLowerCase()
            .trim()
            .replace(/[^a-z0-9-]/g, '-')
            .replace(/^-+|-+$/g, '')
            .substring(0, 214); // npm package name limit
    }

    /**
     * Generate package.json for React (CRA-style)
     */
    private generateReactPackage(base: PackageJson): PackageJson {
        return {
            ...base,
            scripts: {
                start: 'react-scripts start',
                build: 'react-scripts build',
                test: 'react-scripts test',
                eject: 'react-scripts eject',
            },
            dependencies: {
                react: '^18.2.0',
                'react-dom': '^18.2.0',
                'react-scripts': '^5.0.1',
                'react-router-dom': '^6.20.0',
                ajv: '^8.12.0', // Required by react-scripts dependencies
            },
            devDependencies: {
                '@types/react': '^18.2.0',
                '@types/react-dom': '^18.2.0',
                typescript: '^4.9.5', // Compatible with react-scripts 5.0.1
            },
            eslintConfig: {
                extends: ['react-app'],
            } as any,
            browserslist: {
                production: ['>0.2%', 'not dead', 'not op_mini all'],
                development: ['last 1 chrome version', 'last 1 firefox version', 'last 1 safari version'],
            } as any,
        };
    }

    /**
     * Generate package.json for Next.js
     */
    private generateNextJsPackage(base: PackageJson): PackageJson {
        return {
            ...base,
            scripts: {
                dev: 'next dev',
                build: 'next build',
                start: 'next start',
                lint: 'next lint',
            },
            dependencies: {
                react: '^18.2.0',
                'react-dom': '^18.2.0',
                next: '^14.0.0',
            },
            devDependencies: {
                '@types/node': '^20.0.0',
                '@types/react': '^18.2.0',
                '@types/react-dom': '^18.2.0',
                typescript: '^5.0.0',
                eslint: '^8.0.0',
                'eslint-config-next': '^14.0.0',
            },
        };
    }

    /**
     * Generate package.json for Vue
     */
    private generateVuePackage(base: PackageJson): PackageJson {
        return {
            ...base,
            scripts: {
                dev: 'vite',
                build: 'vite build',
                preview: 'vite preview',
            },
            dependencies: {
                vue: '^3.3.0',
            },
            devDependencies: {
                '@vitejs/plugin-vue': '^4.0.0',
                typescript: '^5.0.0',
                vite: '^5.0.0',
                'vue-tsc': '^1.8.0',
            },
        };
    }

    /**
     * Generate package.json for static HTML (with live-server for dev)
     */
    private generateHtmlPackage(base: PackageJson): PackageJson {
        return {
            ...base,
            scripts: {
                dev: 'live-server --port=3000',
                start: 'live-server --port=3000',
            },
            dependencies: {},
            devDependencies: {
                'live-server': '^1.2.2',
            },
        };
    }

    /**
     * Generate minimal package.json for Flutter
     * (Flutter uses pubspec.yaml, not package.json)
     */
    private generateFlutterPackage(base: PackageJson): PackageJson {
        return {
            ...base,
            scripts: {
                dev: 'echo "Flutter uses pubspec.yaml, not package.json"',
            },
            dependencies: {},
        };
    }

    /**
     * Convert package.json object to formatted JSON string
     */
    stringify(packageJson: PackageJson): string {
        return JSON.stringify(packageJson, null, 2);
    }
}
