/**
 * ReactBoilerplateGenerator - Creates React app boilerplate files
 *
 * Generates:
 * - public/index.html
 * - public/manifest.json
 * - src/index.tsx
 * - src/App.tsx (with routing)
 * - src/index.css
 *
 * Validates: Build Mode Requirements - React App Setup
 */

import * as fs from 'fs/promises';
import * as path from 'path';

export interface BoilerplateOptions {
    projectPath: string;
    projectName: string;
    screens: Array<{ id: string; name: string }>;
}

export class ReactBoilerplateGenerator {
    /**
     * Generate all React boilerplate files
     */
    async generate(options: BoilerplateOptions): Promise<void> {
        const { projectPath, projectName, screens } = options;

        console.log('[ReactBoilerplateGenerator] Generating boilerplate files...');

        // Create public/index.html
        await this.createPublicFiles(projectPath, projectName);

        // Create src/index.tsx
        await this.createIndexFile(projectPath);

        // Create src/App.tsx with routing
        await this.createAppFile(projectPath, screens);

        // Create src/index.css
        await this.createStylesFile(projectPath);

        // Create tsconfig.json
        await this.createTsConfigFile(projectPath);

        console.log('[ReactBoilerplateGenerator] Boilerplate files created successfully');
    }

    private async createPublicFiles(projectPath: string, projectName: string): Promise<void> {
        const publicDir = path.join(projectPath, 'public');
        await fs.mkdir(publicDir, { recursive: true });

        // public/index.html
        const indexHtml = `<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <meta name="description" content="${projectName} - Generated by Personaut" />
    <link rel="manifest" href="%PUBLIC_URL%/manifest.json" />
    <title>${projectName}</title>
  </head>
  <body>
    <noscript>You need to enable JavaScript to run this app.</noscript>
    <div id="root"></div>
  </body>
</html>`;

        await fs.writeFile(path.join(publicDir, 'index.html'), indexHtml);

        // public/manifest.json
        const manifest = {
            short_name: projectName,
            name: projectName,
            start_url: ".",
            display: "standalone",
            theme_color: "#000000",
            background_color: "#ffffff"
        };

        await fs.writeFile(
            path.join(publicDir, 'manifest.json'),
            JSON.stringify(manifest, null, 2)
        );
    }

    private async createIndexFile(projectPath: string): Promise<void> {
        const indexTsx = `import React from 'react';
import ReactDOM from 'react-dom/client';
import './index.css';
import App from './App';

const root = ReactDOM.createRoot(
  document.getElementById('root') as HTMLElement
);

root.render(
  <React.StrictMode>
    <App />
  </React.StrictMode>
);`;

        await fs.writeFile(path.join(projectPath, 'src', 'index.tsx'), indexTsx);
    }

    private async createAppFile(
        projectPath: string,
        screens: Array<{ id: string; name: string }>
    ): Promise<void> {
        // Create minimal App.tsx with no page imports
        // Pages will be added incrementally as they're generated
        const appTsx = `import React from 'react';
import { BrowserRouter as Router, Routes, Route, Link } from 'react-router-dom';

function App() {
  return (
    <Router>
      <div className="app">
        <nav className="app-nav">
          {/* Navigation links will be added as pages are created */}
        </nav>
        <main className="app-content">
          <Routes>
            {/* Routes will be added as pages are created */}
          </Routes>
        </main>
      </div>
    </Router>
  );
}

export default App;
`;

        await fs.writeFile(path.join(projectPath, 'src', 'App.tsx'), appTsx);
    }

    /**
     * Add a screen to App.tsx (import, nav link, and route)
     */
    async addScreenToApp(
        projectPath: string,
        screenName: string,
        isFirstScreen: boolean
    ): Promise<void> {
        const appPath = path.join(projectPath, 'src', 'App.tsx');
        let appContent = await fs.readFile(appPath, 'utf-8');

        const componentName = this.toComponentName(screenName);
        const fileName = this.toFileNameWithoutExtension(screenName);
        const route = isFirstScreen ? '/' : `/${this.toRoute(screenName)}`;

        // Add import after the react-router-dom import
        const importStatement = `import ${componentName} from './pages/${fileName}';`;
        appContent = appContent.replace(
            "import { BrowserRouter as Router, Routes, Route, Link } from 'react-router-dom';",
            `import { BrowserRouter as Router, Routes, Route, Link } from 'react-router-dom';
${importStatement}`
        );

        // Add navigation link
        const navLink = `<Link to="${route}">${screenName}</Link>`;
        appContent = appContent.replace(
            '{/* Navigation links will be added as pages are created */}',
            `{/* Navigation links will be added as pages are created */}
          ${navLink}`
        );

        // Add route
        const routeElement = `<Route path="${route}" element={<${componentName} />} />`;
        appContent = appContent.replace(
            '{/* Routes will be added as pages are created */}',
            `{/* Routes will be added as pages are created */}
            ${routeElement}`
        );

        await fs.writeFile(appPath, appContent);
    }

    private async createStylesFile(projectPath: string): Promise<void> {
        const css = `* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Oxygen',
    'Ubuntu', 'Cantarell', 'Fira Sans', 'Droid Sans', 'Helvetica Neue',
    sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

.app {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
}

.app-nav {
  background-color: #282c34;
  padding: 1rem;
  display: flex;
  gap: 1rem;
  flex-wrap: wrap;
}

.app-nav a {
  color: white;
  text-decoration: none;
  padding: 0.5rem 1rem;
  border-radius: 4px;
  transition: background-color 0.2s;
}

.app-nav a:hover {
  background-color: rgba(255, 255, 255, 0.1);
}

.app-content {
  flex: 1;
}`;

        await fs.writeFile(path.join(projectPath, 'src', 'index.css'), css);
    }


    private async createTsConfigFile(projectPath: string): Promise<void> {
        const tsConfig = {
            compilerOptions: {
                target: "es5",
                lib: ["dom", "dom.iterable", "esnext"],
                allowJs: true,
                skipLibCheck: true,
                esModuleInterop: true,
                allowSyntheticDefaultImports: true,
                strict: true,
                forceConsistentCasingInFileNames: true,
                noFallthroughCasesInSwitch: true,
                module: "esnext",
                moduleResolution: "node",
                resolveJsonModule: true,
                isolatedModules: true,
                noEmit: true,
                jsx: "react-jsx"
            },
            include: ["src"]
        };

        await fs.writeFile(
            path.join(projectPath, 'tsconfig.json'),
            JSON.stringify(tsConfig, null, 2)
        );
    }

    private toComponentName(screenName: string): string {
        // "AI Style Assistant & Outfit Planner" -> "AiStyleAssistantOutfitPlanner"
        // Remove special characters and split on spaces/hyphens
        return screenName
            .replace(/[^a-zA-Z0-9\s-]/g, '') // Remove special chars like &, !, etc.
            .split(/[\s-]+/)
            .filter(word => word.length > 0) // Remove empty strings
            .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
            .join('');
    }

    private toFileNameWithoutExtension(screenName: string): string {
        // "AI Style Assistant & Outfit Planner" -> "ai-style-assistant-outfit-planner"
        // Remove special characters, then convert to kebab-case
        return screenName
            .replace(/[^a-zA-Z0-9\s-]/g, '') // Remove special chars like &, !, etc.
            .toLowerCase()
            .replace(/\s+/g, '-')
            .replace(/-+/g, '-'); // Replace multiple hyphens with single hyphen
    }

    private toFileName(screenName: string): string {
        // "Feed Page" -> "feed-page.tsx"
        return screenName.toLowerCase().replace(/\s+/g, '-') + '.tsx';
    }

    private toRoute(screenName: string): string {
        // "Feed Page" -> "feed-page"
        return screenName.toLowerCase().replace(/\s+/g, '-');
    }
}
